# Data Overview

This notebook provides the first structured inspection of the fraud detection dataset. Its purpose is to understand dataset size, schema, data quality, and target distribution before moving into deeper exploratory analysis and model development.

## 1. Objectives

This notebook focuses on the following tasks:

- load the raw dataset using the project data loader
- review dataset shape, columns, and data types
- inspect missing values and duplicate rows
- validate the raw dataset structure
- examine the target distribution
- summarize numerical variables with emphasis on `Time` and `Amount`
- document initial observations for the next stage of EDA

In [1]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.append(str(Path("..").resolve()))

from src.config import NUMERICAL_COLUMNS, TARGET_COLUMN
from src.data.data_loader import load_raw_data
from src.data.data_validation import DataValidationError, validate_raw_data

## 2. Load Data

In [2]:
df = load_raw_data()

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

## 3. Dataset Structure

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("\nColumns:")
print(df.columns.tolist())

Number of rows: 284807
Number of columns: 31

Columns:
['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values
})

    column    dtype
0     Time  float64
1       V1  float64
2       V2  float64
3       V3  float64
4       V4  float64
5       V5  float64
6       V6  float64
7       V7  float64
8       V8  float64
9       V9  float64
10     V10  float64
11     V11  float64
12     V12  float64
13     V13  float64
14     V14  float64
15     V15  float64
16     V16  float64
17     V17  float64
18     V18  float64
19     V19  float64
20     V20  float64
21     V21  float64
22     V22  float64
23     V23  float64
24     V24  float64
25     V25  float64
26     V26  float64
27     V27  float64
28     V28  float64
29  Amount  float64
30   Class    int64

## 4. Data Quality Checks

In [7]:
missing_counts = df.isna().sum()
missing_percent = (df.isna().mean() * 100).round(4)

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
})

missing_summary[missing_summary["missing_count"] > 0].sort_values("missing_count", ascending=False)

Empty DataFrame
Columns: [missing_count, missing_percent]
Index: []

In [8]:
duplicate_count = int(df.duplicated().sum())
print("Duplicate rows:", duplicate_count)

Duplicate rows: 1081

In [9]:
try:
    validate_raw_data(df)
    print("Raw data validation: PASSED")
except DataValidationError as error:
    print("Raw data validation: FAILED")
    print(error)

Raw data validation: PASSED

## 5. Target Variable Overview

In [10]:
target_counts = df[TARGET_COLUMN].value_counts().sort_index()
target_percent = (df[TARGET_COLUMN].value_counts(normalize=True).sort_index() * 100).round(4)

target_summary = pd.DataFrame({
    "count": target_counts,
    "percent": target_percent
})
target_summary.index.name = TARGET_COLUMN
target_summary

        count  percent
Class
0      284315  99.8273
1         492   0.1727

The target distribution should be reviewed carefully because fraud detection is a highly imbalanced classification problem. A very small fraud class means evaluation metrics such as recall, precision, F1-score, and PR-AUC will be more informative than accuracy alone.

## 6. Summary Statistics

In [11]:
df[NUMERICAL_COLUMNS + [TARGET_COLUMN]].describe().T

,count,mean,std,min,25%,50%,75%,max
Time,284807.0,9.481386e+04,47488.145955,0.000000,54201.500000,84692.000000,139320.500000,172792.000000
V1,284807.0,1.175161e-15,1.958696,-56.407510,-0.920373,0.018109,1.315642,2.454930
V2,284807.0,3.384974e-16,1.651309,-72.715728,-0.598550,0.065486,0.803724,22.057729
V3,284807.0,-1.379537e-15,1.516255,-48.325589,-0.890365,0.179846,1.027196,9.382558
V4,284807.0,2.094852e-15,1.415869,-5.683171,-0.848640,-0.019847,0.743341,16.875344
V5,284807.0,1.021879e-15,1.380247,-113.743307,-0.691597,-0.054336,0.611926,34.801666
V6,284807.0,1.494498e-15,1.332271,-26.160506,-0.768296,-0.274187,0.398565,73.301626
V7,284807.0,-5.620335e-16,1.237094,-43.557242,-0.554076,0.040103,0.570436,120.589494
V8,284807.0,1.149614e-16,1.194353,-73.216718,-0.208630,0.022358,0.327346,20.007208
V9,284807.0,-2.414189e-15,1.098632,-13.434066,-0.643098,-0.051429,0.597139,15.594995
V10,284807.0,2.238554e-15,1.088850,-24.588262,-0.535426,-0.092917,0.453923,23.745136
V11,284807.0,1.724421e-15,1.020713,-4.797473,-0.762494,-0.032757,0.739593,12.018913
V12,284807.0,-1.245415e-15,0.999201,-18.683715,-0.405571,0.140033,0.618238,7.848392
V13,284807.0,8.238900e-16,0.995274,-5.791881,-0.648539,-0.013568,0.662505,7.126883
V14,284807.0,1.213481e-15,0.958596,-19.214325,-0.425574,0.050601,0.493150,10.526766
V15,284807.0,4.866699e-15,0.915316,-4.498945,-0.582884,0.048072,0.648821,8.877742
V16,284807.0,1.436219e-15,0.876253,-14.129855,-0.468037,0.066413,0.523296,17.315112
V17,284807.0,-3.768179e-16,0.849337,-25.162799,-0.483748,-0.065676,0.399675,9.253526
V18,284807.0,9.707851e-16,0.838176,-9.498746,-0.498850,-0.003636,0.500807,5.041069
V19,284807.0,1.036249e-15,0.814041,-7.213527,-0.456299,0.003735,0.458949,5.591971
V20,284807.0,6.418678e-16,0.770925,-54.497720,-0.211721,-0.062481,0.133041,39.420904
V21,284807.0,1.628620e-16,0.734524,-34.830382,-0.228395,-0.029450,0.186377,27.202839
V22,284807.0,-3.576577e-16,0.725702,-10.933144,-0.542350,0.006782,0.528554,10.503090
V23,284807.0,2.618565e-16,0.624460,-44.807735,-0.161846,-0.011193,0.147642,22.528412
V24,284807.0,4.473914e-15,0.605647,-2.836627,-0.354586,0.040976,0.439527,4.584549
V25,284807.0,5.109395e-16,0.521278,-10.295397,-0.317145,0.016594,0.350716,7.519589
V26,284807.0,1.686100e-15,0.482227,-2.604551,-0.326984,-0.052139,0.240952,3.517346
V27,284807.0,-3.661401e-16,0.403632,-22.565679,-0.070840,0.001342,0.091045,31.612198
V28,284807.0,-1.227452e-16,0.330083,-15.430084,-0.052960,0.011244,0.078280,33.847808
Amount,284807.0,8.834962e+01,250.120109,0.000000,5.600000,22.000000,77.165000,25691.160000
Class,284807.0,1.727486e-03,0.041527,0.000000,0.000000,0.000000,0.000000,1.000000

In [12]:
df[["Time", "Amount"]].describe().T

,count,mean,std,min,25%,50%,75%,max
Time,284807.0,94813.859575,47488.145955,0.0,54201.5,84692.0,139320.500,172792.00
Amount,284807.0,88.349619,250.120109,0.0,5.6,22.0,77.165,25691.16

## 7. Initial Feature Notes

The dataset contains `Time`, `Amount`, and anonymized features `V1` to `V28`. These `V1` to `V28` variables are PCA-transformed features, which means the original feature names and meanings are not available. This improves confidentiality, but it also limits direct interpretability during EDA and later model explanation.

## 8. Initial Observations

- the dataset is large enough for meaningful fraud analysis
- the target variable is expected to be highly imbalanced, which will affect model evaluation strategy
- `Time` and `Amount` are the most directly interpretable numerical variables
- the PCA-based variables contain predictive information, but their business interpretation is limited
- data quality findings from missing values and duplicates should guide the next cleaning and EDA steps

## 9. Next Step

The next notebook should be `03_univariate_analysis.ipynb`. It will focus on single-variable analysis, including feature distributions, outlier behavior, and target-wise inspection of important variables.